# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (26 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://gitlab.com/SamB440/tale-of-kingdoms/issues/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="taleofkingdoms" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Tale of Kingdoms: A new Conquest" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.islandearth.net" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="636453830200432875.png" #optional
# A text field displayed in the mod UI
credits="Marackai, Aksel, and Pyro for keeping me going (and their translations!). Tyberalyx for creating the mod in the first place. Michaelb229 and his team for building." #optional
# A text field displayed in the mod UI
authors="SamB440" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''This mod is in alpha. Use at your own risk! 

The Tale of Kingdoms mod, revived.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.taleofkingdoms]] #optional
    # the modid of the dependency
    modId="worldedit" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[7.1.0;48cc31c]" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
